Bump version to 1.4, remove patch, configure

diff --git a/openjpeg.SlackBuild b/openjpeg.SlackBuild
--- a/openjpeg.SlackBuild
+++ b/openjpeg.SlackBuild
@@ -19,16 +19,17 @@
 #
 # Visit SlackPack at http://sotirov-bg.net/slackpack/
 #
-# $Id: openjpeg.SlackBuild,v 1.1 2010/10/03 22:07:07 gsotirov Exp $
+# $Id: openjpeg.SlackBuild,v 1.2 2011/02/13 16:01:16 gsotirov Exp $
 #
 
 . ../slack-package.conf
 
 NAME=OpenJPEG
 PNAME=`echo $NAME | tr "[:upper:]" "[:lower:]"`
-VERSION=1.3
+VERSION=1.4
 VER_MAJ=1
-VER_MIN=3
+VER_MIN=4
+VER_REV=697
 ARCH=${ARCH:-i486}
 BUILD=${BUILD:-1}
 
@@ -39,7 +40,7 @@ if [ ! -e $TMP ]; then
   mkdir -p $TMP # location to build the source
 fi
 
-SRC=$TMP/${NAME}_v${VER_MAJ}_${VER_MIN}
+SRC=$TMP/${PNAME}_v${VER_MAJ}_${VER_MIN}_sources_r${VER_REV}
 if [ -e $SRC -a -d $SRC ]; then
   echo "Source directory '$SRC' already exists! Plaese, move it or remove it."
   exit 1
@@ -54,23 +55,36 @@ mkdir -p $PKG
 
 # Extract the source
 cd $TMP
-tar -xvf $CWD/${PNAME}_v${VER_MAJ}_${VER_MIN}.tar.gz || exit 1
+tar -xvf $CWD/${PNAME}_v${VER_MAJ}_${VER_MIN}_sources_r${VER_REV}.tgz || exit 1
 cd $SRC
 fix_source
 
-# Apply patches
-patch -p1 -b -z.orig <$CWD/$PNAME-$VERSION.diff
+# Configure
+CFLAGS=$SLKCFLAGS \
+CXXFLAGS=$SLKCFLAGS \
+./configure --build=$ARCH-slackware-linux \
+            --host=$ARCH-slackware-linux \
+            --prefix=/usr \
+            --sysconfdir=/etc \
+            --mandir=/usr/man \
+            --docdir=/usr/doc/$NAME-$VERSION \
+            --enable-shared=yes \
+            --enable-static=no \
+            --enable-png \
+            --enable-tiff \
+            --enable-lcms1 || exit 2
 
 # Build & install
-MYCFLAGS="$SLKCFLAGS" make || exit 3
-make DESTDIR=$PKG install
+# No -j flag, because of build system fail
+make || exit 3
+( cd doc; make; make mandir=$PKG/usr/man install )
+
+make DESTDIR=$PKG install || exit 4
 
 # Prepare
 bin_perms $PKG
 ( cd $PKG; strip_bin; strip_lib )
-DOCFILES="$DOCFILES license.txt"
 ( cd $SRC; create_docs $PKG $PNAME-$VERSION )
-( cd $PKG/usr/doc/$PNAME-$VERSION; cat license.txt | tr "[\r]" "[\n]" > COPYING )
 gzip_man $PKG
 
 mkdir -p $PKG/install
@@ -81,7 +95,6 @@ SBDIR=$PKG/usr/src/slackbuilds/$PNAME-$VERSION
 mkdir -p $SBDIR
 install -m 644 $CWD/slack-desc           $SBDIR/slack-desc
 install -m 644 $CWD/slack-required       $SBDIR/slack-required
-install -m 644 $CWD/$PNAME-$VERSION.diff $SBDIR/$PNAME-$VERSION.diff
 install -m 644 $CWD/$PNAME.SlackBuild    $SBDIR/$PNAME.SlackBuild
 
 # Assemble
